### ISSUE TITLE
Foreign key exception for person.UserRoleId is weird

### ISSUE THREAD

**Issue by Smao0875** [Smao0875/TCMManagement#5]
Steps to produce:
1. open swagger page and go to **POST** /api/person
2. Create a normal person with a valid UserRoleId. 
 Works fine.
3. Create a normal person with a invalid UserRoleId such as **9.**
We will get such **exception** message:
System.Data.SqlClient.SqlException: The INSERT statement conflicted with the FOREIGN KEY constraint \"FK_dbo.People_dbo.UserRoles_UserRoleId\". The conflict occurred in database \"TCMManagement.Models.TcmContext\", table \"dbo.UserRoles\", column \u0027UserRoleId\u0027.\r\nThe statement has been terminated.\

Here is the SQL query:
INSERT [dbo].[People]([FirstName], [LastName], [Email], [Gender], [DateCreated], [Phone], [Note], [Password], [**UserRoleId**], [IsDeleted])
VALUES (@0, @1, @2, @3, @4, @5, @6, @7, @8, @9)
SELECT [PersonId]
FROM [dbo].[People]
WHERE @@ROWCOUNT > 0 AND [PersonId] = scope_identity()

-- @0: 'string' (Type = String, Size = -1)

-- @1: 'string' (Type = String, Size = -1)

-- @2: '66' (Type = String, Size = -1)

-- @3: 'string' (Type = String, Size = -1)

-- @4: '3/8/2018 8:48:27 PM' (Type = DateTime2)

-- @5: 'string' (Type = String, Size = -1)

-- @6: 'string' (Type = String, Size = -1)

-- @7: 'string' (Type = String, Size = -1)

**-- @8: '9' (Type = Int32)**

-- @9: 'False' (Type = Boolean)

-- Executing at 3/8/2018 4:39:11 PM -05:00

4. Create a normal person with a valid UserRoleId **1.** 
We are going to get the same **exception** message as **step 3.** And here is the SQL query
Started transaction at 3/8/2018 4:40:23 PM -05:00

INSERT [dbo].[People]([FirstName], [LastName], [Email], [Gender], [DateCreated], [Phone], [Note], [Password], [**UserRoleId**], [IsDeleted])
VALUES (@0, @1, @2, @3, @4, @5, @6, @7, @8, @9)
SELECT [PersonId]
FROM [dbo].[People]
WHERE @@ROWCOUNT > 0 AND [PersonId] = scope_identity()

-- @0: 'string' (Type = String, Size = -1)

-- @1: 'string' (Type = String, Size = -1)

-- @2: '66' (Type = String, Size = -1)

-- @3: 'string' (Type = String, Size = -1)

-- @4: '3/8/2018 8:48:27 PM' (Type = DateTime2)

-- @5: 'string' (Type = String, Size = -1)

-- @6: 'string' (Type = String, Size = -1)

-- @7: 'string' (Type = String, Size = -1)

**-- @8: '9' (Type = Int32)**

-- @9: 'False' (Type = Boolean)

-- Executing at 3/8/2018 4:40:23 PM -05:00

**-- Failed in 1 ms with error: The INSERT statement conflicted with the FOREIGN KEY constraint "FK_dbo.People_dbo.UserRoles_UserRoleId". The conflict occurred in database "TCMManagement.Models.TcmContext", table "dbo.UserRoles", column 'UserRoleId'.
The statement has been terminated.**

5. If we stop and restart debug process then it will work fine.

It seems that the invalid UserRoleId will be always there there once it is invalid.
The whole Person created with the invalid UserRoleId will be staying there.

Like a buffer never get flushed.

I did some research but couldn't get a solution.
Could you please take a look when you have time?

Thanks.

**Comment by Smao0875** [comment]
I am not assigning this to you.
Just try to get some other ideas.

I think there is a work around.
This exception is thrown from **context.SaveChanges();**
I can avoid this issue by validating our foreign key before we call this function.
-- It won't solve this problem, though.

**Comment by JenHZ** [comment]
Sure, I will take a look.

**Comment by JenHZ** [comment]
I have a question, not specific for this issue. Should we prevent adding person with UserRoleId = 1 (which is a patient) to person table ?

**Comment by JenHZ** [comment]
May need try catch to fix this bug.

**Comment by Smao0875** [comment]
I don't quite understand how try/catch would fix this issue.
But I will try anyway.

**Comment by JenHZ** [comment]
The basic idea about try/catch will be :  
try
{
    SaveChanges();
}
catch(...)
{
  // clear the cached but not saved entity
   context.People.Local.Clear()
}

Then we should not get the exception in next time when we add a valid people.
However, I don't think this is a proper way. We should avoid add the invalid people entity to the table. So the workaround you mentioned is a better way, I believe.
I will implement that.

**Comment by Smao0875** [comment]
Good job!
